package com.sgauto.app.enums;

public enum PermissaoChave {
    // MÓDULO: USUÁRIOS E SEGURANÇA
    USUARIO_VISUALIZAR,
    USUARIO_CRIAR,
    USUARIO_EDITAR,
    USUARIO_ALTERAR_SENHA,
    USUARIO_EXCLUIR,
    PERFIL_VISUALIZAR,
    PERFIL_GERENCIAR,

    // MÓDULO: CADASTROS BÁSICOS
    CLIENTE_VISUALIZAR,
    CLIENTE_CRIAR,
    CLIENTE_EDITAR,
    CLIENTE_EXCLUIR,
    VEICULO_VISUALIZAR,
    VEICULO_CRIAR,
    VEICULO_EDITAR,
    VEICULO_EXCLUIR,

    // MÓDULO: RECURSOS HUMANOS
    FUNCIONARIO_VISUALIZAR,
    FUNCIONARIO_CRIAR,
    FUNCIONARIO_EDITAR,
    FUNCIONARIO_EXCLUIR,
    FUNCIONARIO_OPCOES_AVANCADAS,

    // MÓDULO: CATÁLOGO E ESTOQUE
    PECA_VISUALIZAR,
    PECA_CRIAR,
    PECA_EDITAR,
    PECA_EXCLUIR,
    MODELOS_CRIAR,
    MODELOS_EDITAR,
    SERVICO_VISUALIZAR,
    SERVICO_GERENCIAR,
    CATEGORIA_GERENCIAR,

    // MÓDULO: OPERACIONAL (ORDEM DE SERVIÇO)
    OS_VISUALIZAR,
    OS_CRIAR,
    OS_EDITAR,
    OS_APROVAR,
    OS_FINALIZAR,
    OS_CANCELAR,

    // MÓDULO: PÁTIO E ESTADIA
    PATIO_VISUALIZAR,
    PATIO_ENTRADA,
    PATIO_SAIDA,
    PATIO_CONFIGURAR,

    // MÓDULO: FINANCEIRO E CAIXA
    CAIXA_VISUALIZAR,
    CAIXA_FECHAR,
    CAIXA_MOVIMENTAR,
    CAIXA_FINANCEIRO_RELATORIOS,

    // MÓDULO: SISTEMA
    CONFIGURACOES_VISUALIZAR,
    CONFIGURACOES_EDITAR
}
