INSERT INTO t_config (config_chave, config_valor, config_data_criacao, config_data_atualizacao)
VALUES
    ('BACKUP_PASTA_LOCAL', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BACKUP_PASTA_NUVEM', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BACKUP_AUTOMATICO_ATIVO', 'true', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BACKUP_INTERVALO_DIAS', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BACKUP_APOS_FECHAMENTO_CAIXA', 'true', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);